### ISSUE TITLE
jenkins-cli might not be needed on jenkins server

### ISSUE THREAD

**Issue by cr3** [ICTO/ansible-jenkins#7]
The "Restart Jenkins" handler uses {{ jenkins.cli_dest }} to restart the service which assumes that the client is running on the server. This is not strictly necessary though and a Jenkins server can exist without having a client running on it. So, it might be preferable to define the handler as:

``` yaml
- name: Restart Jenkins
  sudo: True
  service: name=jenkins state=restarted
```
